In [1]:
import numpy as np

In [2]:
X = np.array([[1., -2., 2.],
              [-2., 1., 3.],
              [4., 1., -2.]])

In [4]:
print(X)

[[ 1. -2.  2.]
 [-2.  1.  3.]
 [ 4.  1. -2.]]


In [5]:
from sklearn.preprocessing import MinMaxScaler  # nie nadaje się gdy mamy ekstremalne outliery

scaler = MinMaxScaler()
scaler.fit(X)
print(scaler.transform(X))

[[0.5 0.  0.8]
 [0.  1.  1. ]
 [1.  1.  0. ]]


In [6]:
from sklearn.preprocessing import RobustScaler  # nadaje się do danych gdize mamy duzo outlierów, mediana, kwartyle

In [8]:
scaler2 = RobustScaler()
scaler2.fit(X)
print(scaler2.transform(X))

[[ 0.  -2.   0. ]
 [-1.   0.   0.4]
 [ 1.   0.  -1.6]]


In [9]:
from sklearn.preprocessing import MaxAbsScaler  # zachowuje znak danych

scaler3 = MaxAbsScaler()
scaler3.fit(X)
print(scaler3.transform(X))

[[ 0.25       -1.          0.66666667]
 [-0.5         0.5         1.        ]
 [ 1.          0.5        -0.66666667]]


In [10]:
from sklearn.preprocessing import StandardScaler  # srednia i odchylenie std

scaler4 = StandardScaler()
scaler4.fit(X)
print(scaler4.transform(X))

[[ 0.         -1.41421356  0.46291005]
 [-1.22474487  0.70710678  0.9258201 ]
 [ 1.22474487  0.70710678 -1.38873015]]


In [11]:
# binaryzacja
from sklearn.preprocessing import binarize

print(binarize(X, threshold=0.5))

[[1. 0. 1.]
 [0. 1. 1.]
 [1. 1. 0.]]


In [12]:
import numpy as np
import matplotlib.pyplot as plt

X = np.array([[1., 2., 20.],
              [2., 1., 3.],
              [4., 1., 0.02]])

In [13]:
print(np.log(X+1))

[[0.69314718 1.09861229 3.04452244]
 [1.09861229 0.69314718 1.38629436]
 [1.60943791 0.69314718 0.01980263]]
