In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
from scipy.spatial.distance import mahalanobis
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy import linalg

In [4]:
!pip install scikit-learn

   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------  8.7/8.7 MB 61.1 MB/s eta 0:00:01
   ---------------------------------------- 8.7/8.7 MB 49.6 MB/s eta 0:00:00

   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import silhouette_score
from sklearn.manifold import TSNE
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, cross_val_score  # podziały i walidacja
from sklearn.datasets import load_wine, load_diabetes

In [7]:
np.random.seed(42)

In [8]:
# liczba obserwacji
n = 300

x1 = np.random.normal(0, 2, n)
x2 = 0.8 * x1 + np.random.normal(0, 2, n)
x3 = np.random.normal(5, 5, n)
x4 = -0.5 * x1 + 0.3 * x3 + np.random.normal(0, 2, n)

In [9]:
# robimy macierze
X = np.column_stack([x1, x2, x3, x4])
df = pd.DataFrame(X, columns=["x1", "x2", "x3", "x4"])

In [10]:
# Liczymy macierze kowariancji i koralacji
Sigma = np.cov(X, rowvar=False) # rowvar=False => kolumny to zmienne
R = np.corrcoef(X, rowvar=False)

In [11]:
print("Macierz kowariancji Sigma:", np.round(Sigma, 3))
print("Macierz korelacji R:", np.round(R, 3))

Macierz kowariancji Sigma: [[ 3.875  2.946 -0.371 -1.777]
 [ 2.946  5.933 -0.597 -1.624]
 [-0.371 -0.597 24.834  7.544]
 [-1.777 -1.624  7.544  7.067]]
Macierz korelacji R: [[ 1.     0.614 -0.038 -0.34 ]
 [ 0.614  1.    -0.049 -0.251]
 [-0.038 -0.049  1.     0.569]
 [-0.34  -0.251  0.569  1.   ]]
