# Biblioteka NumPy
Napisana w C do szybkich operacji na tablicach\
ndarray - tablica w NumPy

In [2]:
# instalacja biblioteki
!pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 9.2 MB/s eta 0:00:02
   ---------------------------------------  12.6/12.8 MB 35.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 35.5 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 11.2 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np  # alias

In [4]:
print(np.__version__)

2.3.4


In [5]:
lista = [2, 4, 6, 8, 10]
lista

[2, 4, 6, 8, 10]

In [6]:
a = np.array(lista)
a

array([ 2,  4,  6,  8, 10])

In [7]:
a.dtype  # typ danych

dtype('int64')

int64 - int 8 bajtowy

In [8]:
print(np.iinfo(np.int64))

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [9]:
print(type(a))

<class 'numpy.ndarray'>


In [11]:
# kształt
a.shape

(5,)

In [12]:
p = np.zeros((3, 3))
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
print(p)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print(p.dtype)

float64


In [17]:
print(np.finfo(np.float64))

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
smallest_normal = 2.2250738585072014e-308   smallest_subnormal = 4.9406564584124654e-324
---------------------------------------------------------------



In [18]:
q = np.ones((2, 2))
print(q)
q.dtype

[[1. 1.]
 [1. 1.]]


dtype('float64')

In [19]:
r = np.full((2, 2), 4)
print(r)
r.dtype

[[4 4]
 [4 4]]


dtype('int64')

In [20]:
s = np.eye(4)
print(s)
s.dtype

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


dtype('float64')